src/screens/MainPageAfter/MainPageAfter.css
src/screens/MainPageBefore/MainPageBefore.css

JIRA: GUC-92
resolves: #22
- 관련 티켓: [GUC-92](https://sh0314.atlassian.net/browse/GUC-92)
- 관련 GitHub 이슈: #22 
---
- 변경 사항 설명:
- 메인페이지 css 수정
---
- UI 확인, 코드 컨벤션 확인
---
---
---
[GUC-92]: https://sh0314.atlassian.net/browse/GUC-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 메인페이지 css 수정

---

eslint.config.js
src/App.jsx
src/icons/UserEditIcon/UserEditIcon.jsx
src/icons/XButton/XButton.jsx
src/screens/EditUser/EditUser.css
src/screens/EditUser/EditUser.jsx
src/screens/EmailScreen/EmailScreen.css
src/screens/EmailScreen/EmailScreen.jsx
src/screens/MyPage/MyPage.jsx
src/screens/NicknameScreen/NicknameScreen.css
src/screens/NicknameScreen/NicknameScreen.jsx
src/screens/PasswordScreen/PasswordScreen.css
src/screens/PasswordScreen/PasswordScreen.jsx
vite.config.js

- 관련 티켓: [GUC-105](https://sh0314.atlassian.net/browse/GUC-105)
- 관련 GitHub 이슈: #35 
---
- 변경 사항 설명:
- UserEditIcon 아이콘 컴포넌트화
- 회원정보 수정페이지 제작
- 닉네임 중복 확인 팝업 페이지 제작
- 이름 수정 기능 추가
- 비밀번호 팝업 페이지 제작
- 이메일변경 팝업 페이지 제작
- 깃허브 링크 수정 기능 추가
- 깃허브 링크 유효성 검사 추가
---
- 상태관리 zustand로 코드 리팩토링 할 예정
- UI 확인, 코드 구조 확인
---
---
---
[GUC-105]: https://sh0314.atlassian.net/browse/GUC-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

회원정보 수정페이지 제작

---

src/App.jsx
src/screens/RoadMap/RoadMap.jsx

- 관련 티켓: [GUC-138](https://sh0314.atlassian.net/browse/GUC-138)
- 관련 GitHub 이슈: #47 
---
- 변경 사항 설명:
- RoadMapBefore 파일명 수정
- 파일 경로 수정
---
- ex) 경로 오류 확인
---
---
---
[GUC-138]: https://sh0314.atlassian.net/browse/GUC-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

로드맵페이지 버그 수정

---

package-lock.json
package.json
src/SSEAlarmConnector.jsx
src/screens/Notice/Notice.css
src/screens/Notice/Notice.jsx

- 관련 티켓: [GUC-147](https://sh0314.atlassian.net/browse/GUC-147)
- 관련 GitHub 이슈: #53 
---
- 배포 되어있는 API를 호출하도록 변경했습니다.
---
---
---
---
[GUC-147]: https://sh0314.atlassian.net/browse/GUC-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

localhost -> 배포 IP로 변경

---

src/components/ChatImageMessage.jsx
src/components/MessageInputBox/MessageInputBox.css
src/components/MessageInputBox/MessageInputBox.jsx
src/icons/ImageIcon/ImageIcon.css
src/icons/ImageIcon/ImageIcon.jsx
src/icons/SearchIcon/SearchIcon.jsx
src/screens/Message/Message.jsx
src/screens/MessageRoom/MessageRoom.css
src/screens/MessageRoom/MessageRoom.jsx

- 관련 티켓: [GUC-173](https://sh0314.atlassian.net/browse/GUC-173)
- 관련 GitHub 이슈: #67 
---
- 채팅 기능에 사진을 전송하고 조회 할 수 있도록 기능을 추가했습니다.
- 검색 기능을 추가하여 키워드 검색 시 해당 키워드로 이동 되도록 기능을 추가했습니다.
- 채팅방 내부 날짜 포멧 변경
- 오후/오전 시:분
- 날짜가 변경 되면 메시지와 메시지 사이에 월/일이 표시되어있는 구분 박스 추가 
---
---
---
사진 조회
검색
날짜 변경
---
[GUC-173]: https://sh0314.atlassian.net/browse/GUC-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

채팅 사진 전송,조회 / 검색 기능 추가

---

src/screens/Write/Write.css
src/screens/Write/Write.jsx

JIRA: GUC-185
resolves: #78
- 관련 티켓: [GUC-185](https://sh0314.atlassian.net/browse/GUC-185)
- 관련 GitHub 이슈: #78 
---
- 변경 사항 설명:
- 태그 추출 API 연결했습니다.
- 깃허브 URL 입력 칸 만들었습니다.
---
- UI 어때요?
---
---
---
[GUC-185]: https://sh0314.atlassian.net/browse/GUC-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 태그 추출 API 연결

---

package-lock.json
package.json
src/App.jsx
src/hooks/useMainUserInfo.js
src/screens/Login/AuthCallBack.jsx
src/screens/Login/Login.jsx
src/screens/Login/SocialKakao.jsx
src/screens/MainPageAfter/MainPageAfter.jsx

- 관련 티켓: [GUC-XX](https://sh0314.atlassian.net/browse/GUC-XX)
- 관련 GitHub 이슈: #XX
---
- 변경 사항 설명:
- 여기에 어떤 변경을 했는지 설명해주세요
- ex) 로그인 성공 시 홈으로 리디렉션되도록 수정함
---
---
---
---

feat: 카카오 소셜 로그인 테스트

---

src/App.jsx
src/components/RecruitButton/RecruitButton.jsx
src/screens/Community/Community.jsx
src/screens/CommunityWrite/CommunityWrite.css
src/screens/CommunityWrite/CommunityWrite.jsx

- 관련 티켓: [GUC-183]
- 관련 GitHub 이슈: #75
---
- 커뮤니티 글쓰기 페이지 구현
---
- 툴바 작동 여부
---
---
---
[GUC-183]: https://sh0314.atlassian.net/browse/GUC-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Generate a community-write page

---

src/App.jsx
src/icons/AlogLogo/AlogLogo.jsx
src/screens/CommunityViewPost/CommunityViewPost.css
src/screens/CommunityViewPost/CommunityViewPost.jsx
src/screens/CommunityWrite/CommunityWrite.jsx

- 관련 티켓: [GUC-191]
- 관련 GitHub 이슈: #86
---
- 변경 사항 설명:
- 커뮤니티 글 보기 페이지 제작
---
---
---
[GUC-191]: https://sh0314.atlassian.net/browse/GUC-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

generate community post view page

---

src/screens/Write/Write.css
src/screens/Write/Write.jsx

JIRA: GUC-196
resolves: #91
- 관련 티켓: [GUC-196](https://sh0314.atlassian.net/browse/GUC-196)
- 관련 GitHub 이슈: #91 
---
- 변경 사항 설명:
- 요약 서비스랑 api 연결했어요
- 요약 중에는 발행하기 버튼이 보이지 않게 하였습니다.
- refresh 버튼은 따로 넣지 않았고, 에러 발생 시 다시 게시하기 버튼을 누르도록 유도했습니다.
---
- 그냥 요약 중... 잠시만 기다려주세요! 이런 식으로 문구를 넣었는데 괜찮을지 의견주세요.
- 어색한 부분 있으면 알려주세요
---
---
- 정상 처리시
- 에러 처리시
[GUC-196]: https://sh0314.atlassian.net/browse/GUC-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: summarize 서비스 api 연결, FE 팝업 로직 수정

---

src/App.jsx
src/screens/PortfolioView/PortfolioView.css
src/screens/PortfolioView/PortfolioView.jsx

- 관련 티켓: [GUC-203](https://sh0314.atlassian.net/browse/GUC-203)
- 관련 GitHub 이슈: #99 
---
- 변경 사항 설명:
- 포트폴리오 view 페이지 생성
---
---
---
---
[GUC-203]: https://sh0314.atlassian.net/browse/GUC-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat/포트폴리오 view 페이지 제작

---

src/screens/PortfolioView/PortfolioView.css
src/screens/PortfolioView/PortfolioView.jsx
src/screens/PortfolioWrite/PortfolioWrite.jsx

JIRA: GUC-218
resolves: #116
- 관련 티켓: [GUC-218](https://sh0314.atlassian.net/browse/GUC-218)
- 관련 GitHub 이슈: #116 
---
- 변경 사항 설명:
- 포트폴리오 삭제 API
- 포트폴리오 업데이트 API
---
---
---
---
[GUC-218]: https://sh0314.atlassian.net/browse/GUC-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 포트폴리오 삭제, 업데이트 API 연결

---

src/components/SortButton/SortButton.css
src/components/SortButton/SortButton.jsx
src/screens/Community/Community.css
src/screens/Community/Community.jsx

- 관련 GitHub 이슈: #131
---
- 변경 사항 설명:
- 커뮤니티 정렬 버튼 추가
---
---
---
---

feat:커뮤니티 페이지 정렬 버튼 추가

---

src/App.jsx
src/components/CommunityPostList/CommunityPostList.jsx
src/components/PostComponent/PostComponent.jsx
src/constants/categories.js
src/screens/CommunityViewPost/CommunityViewPost.css
src/screens/CommunityViewPost/CommunityViewPost.jsx
src/screens/CommunityWrite/CommunityWrite.jsx
src/screens/MainPageAfter/MainPageAfter.jsx
src/screens/MainPageBefore/MainPageBefore.jsx
src/screens/ViewPost/ViewPost.jsx
src/screens/Write/Write.jsx

- 관련 티켓: [GUC-244](https://sh0314.atlassian.net/browse/GUC-244)
- 관련 GitHub 이슈: close #144 
---
- 변경 사항 설명:
커뮤니티 글 CRUD
https://github.com/user-attachments/assets/eb417fff-29ef-4abe-83cb-6c1f8ecb15f3
---
---
---
---
[GUC-244]: https://sh0314.atlassian.net/browse/GUC-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat : 커뮤니티 글 CRUD API 연결

---

src/screens/ForgotPassword/ForgotPassword.css
src/screens/ForgotPassword/ForgotPassword.jsx
src/screens/ResetPassword/ResetPassword.css
src/screens/ResetPassword/ResetPassword.jsx

- 관련 GitHub 이슈: #131
---
- 변경 사항 설명:
- 비밀번호 찾기 UI 개선
- 비밀번호 재설정 UI 개선
---
---
---
요랬는데
요래대씀당
---

fix: 비밀번호 찾기, 비밀번호 재설정 페이지 UI 개선

---

src/components/GenerateReadme/GenerateReadme.jsx
src/components/Historys/Historys.jsx
src/screens/GenerateReadmeScreen/GenerateReadmeScreen.css
src/screens/GenerateReadmeScreen/GenerateReadmeScreen.jsx

- 관련 GitHub 이슈: #131
---
- 변경 사항 설명:
- README 페이지 너무 휑해서 서비스 소개 문구 추가
- 버튼 영어 -> 한국어 변경
---
---
---
> <img width="1582" alt="image" src="https://github.com/user-attachments/assets/22fc243b-b700-4fdf-9ba6-bbcd74307c24" />
요랬는데
요래대씀당
---

feat:readme생성 페이지 문구 추가 및 버튼 영어->한국어 변경

---

src/components/ComponentSeeAll/ComponentSeeAll.jsx
src/components/FollowButton/FollowButton.jsx
src/components/FollowDelete/FollowDelete.jsx
src/components/FollowTab/FollowTab.jsx
src/components/LoginComponent/LoginComponent.jsx
src/components/LogoutButtonComponent/LogoutButtonComponent.css
src/components/LogoutButtonComponent/LogoutButtonComponent.jsx
src/components/MyPost/MyPost.jsx
src/components/UnfollowComponent/UnfollowComponent.jsx
src/screens/GenerateReadmeScreen/GenerateReadmeScreen.jsx
src/screens/MyBlog/MyBlog.jsx

- 관련 GitHub 이슈: #131
---
- 변경 사항 설명:
- 버튼 영어->한국어 변경
---
---
---
---

Fix/guc 232 UI improve

---

src/components/MatchingModal/MatchingModal.jsx
src/components/MyPost/MyPost.jsx
src/screens/Blog/Blog.css
src/screens/Blog/Blog.jsx
src/screens/CommunityViewPost/CommunityViewPost.jsx
src/screens/DeleteNotice/DeleteNotice.css
src/screens/EditUser/EditUser.jsx
src/screens/MainPageAfter/MainPageAfter.css
src/screens/MainPageAfter/MainPageAfter.jsx
src/screens/MainPageBefore/MainPageBefore.css
src/screens/MainPageBefore/MainPageBefore.jsx
src/screens/MyBlog/MyBlog.css
src/screens/MyBlog/MyBlog.jsx
src/screens/MyPage/MyPage.jsx
src/screens/ViewPost/ViewPost.jsx

- 관련 GitHub 이슈: #153 
---
- 변경 사항 설명:
- 무한요청 해결
- 알림 전체삭제 팝업 Ui 개선
---
- 프사 무한 요청 문제 해결 됐는지
---
---
---

fix:무한요청 해결 및 알림 삭제 팝업 ui 개선

---

src/screens/Write/Write.jsx

JIRA: GUC-256
resolves: #166
- 관련 티켓: [GUC-256](https://sh0314.atlassian.net/browse/GUC-256)
- 관련 GitHub 이슈: #166 
---
- 변경 사항 설명:
- 요약 팝업에서 글 지울 시 커서 맨 뒤로 이동하는 오류 수정
---
---
---
---
[GUC-256]: https://sh0314.atlassian.net/browse/GUC-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 요약 팝업 지울 시 커서 이동 오류

---

src/screens/MainPageAfter/MainPageAfter.css
src/screens/MainPageAfter/MainPageAfter.jsx
src/screens/MainPageBefore/MainPageBefore.css
src/screens/MainPageBefore/MainPageBefore.jsx
src/screens/MyBlog/MyBlog.css
src/screens/MyBlog/MyBlog.jsx

- 관련 티켓: [GUC-252](https://sh0314.atlassian.net/browse/GUC-252)
- 관련 GitHub 이슈: #156 
---
- 변경 사항 설명:
- 마이블로그 css 수정
- 메인페이지 css, 로직 수정
---
- UI 확인
- 로직 확인
---
---
---
[GUC-252]: https://sh0314.atlassian.net/browse/GUC-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

마이블로그, 메인페이지 수정

---

src/components/FollowButton/FollowButton.css
src/components/GoGitHub/GoGitHub.jsx
src/components/GoPortfolio/GoPortfolio.jsx
src/screens/Blog/Blog.css
src/screens/Blog/Blog.jsx
src/screens/MyPage/MyPage.jsx

- 관련 티켓: [GUC-268](https://sh0314.atlassian.net/browse/GUC-268)
- 관련 GitHub 이슈: #187
---
- 변경 사항 설명:
- 남 블로그 ui 수정
---
---
---
---
[GUC-268]: https://sh0314.atlassian.net/browse/GUC-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

남 블로그 홈 ui 수정

---

src/components/CommunityPostList/CommunityPostList.jsx
src/components/CommunityTab/CommunityTab.jsx
src/screens/Community/Community.jsx

- 관련 티켓: [GUC-270](https://sh0314.atlassian.net/browse/GUC-270)
- 관련 GitHub 이슈: #191 
---
- 커뮤니티 정렬, 검색 추가
---
---
---
---

커뮤니티 분류 정렬, 검색 추가

---

src/screens/MainPageAfter/MainPageAfter.css
src/screens/MainPageAfter/MainPageAfter.jsx
src/screens/MainPageBefore/MainPageBefore.css

- 관련 티켓: [GUC-267](https://sh0314.atlassian.net/browse/GUC-267)
- 관련 GitHub 이슈: #186
---
- 변경 사항 설명:
- 메인페이지 카테고리 ui변경
---
---
---
---
[GUC-267]: https://sh0314.atlassian.net/browse/GUC-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

카테고리 탭 선택시 카테고리 선택 형식 드롭다운 -> 전체 노출 변경
